export const NCR_REGION = "NCR";

const buildNumberedBarangays = (
  city: string,
  start: number,
  end: number,
  extras: string[] = [],
) => {
  const numbered = Array.from({ length: end - start + 1 }, (_, index) => {
    return `Barangay ${index + start}`;
  });

  return [...numbered, ...extras].map((barangay) => ({
    city,
    barangay,
  }));
};

const namedLocations: Array<{ city: string; barangay: string }> = [
  // Las Pi�as
  { city: "Las Pi�as", barangay: "Almanza Dos" },
  { city: "Las Pi�as", barangay: "Almanza Uno" },
  { city: "Las Pi�as", barangay: "B. F. International Village" },
  { city: "Las Pi�as", barangay: "Daniel Fajardo" },
  { city: "Las Pi�as", barangay: "Elias Aldana" },
  { city: "Las Pi�as", barangay: "Ilaya" },
  { city: "Las Pi�as", barangay: "Manuyo Dos" },
  { city: "Las Pi�as", barangay: "Manuyo Uno" },
  { city: "Las Pi�as", barangay: "Pamplona Dos" },
  { city: "Las Pi�as", barangay: "Pamplona Tres" },
  { city: "Las Pi�as", barangay: "Pamplona Uno" },
  { city: "Las Pi�as", barangay: "Pilar" },
  { city: "Las Pi�as", barangay: "Pulang Lupa Dos" },
  { city: "Las Pi�as", barangay: "Pulang Lupa Uno" },
  { city: "Las Pi�as", barangay: "Talon Dos" },
  { city: "Las Pi�as", barangay: "Talon Kuatro" },
  { city: "Las Pi�as", barangay: "Talon Singko" },
  { city: "Las Pi�as", barangay: "Talon Tres" },
  { city: "Las Pi�as", barangay: "Talon Uno" },
  { city: "Las Pi�as", barangay: "Zapote" },

  // Makati
  { city: "Makati", barangay: "Bangkal" },
  { city: "Makati", barangay: "Bel-Air" },
  { city: "Makati", barangay: "Carmona" },
  { city: "Makati", barangay: "Cembo" },
  { city: "Makati", barangay: "Comembo" },
  { city: "Makati", barangay: "Dasmari�as" },
  { city: "Makati", barangay: "East Rembo" },
  { city: "Makati", barangay: "Forbes Park" },
  { city: "Makati", barangay: "Guadalupe Nuevo" },
  { city: "Makati", barangay: "Guadalupe Viejo" },
  { city: "Makati", barangay: "Kasilawan" },
  { city: "Makati", barangay: "La Paz" },
  { city: "Makati", barangay: "Magallanes" },
  { city: "Makati", barangay: "Olympia" },
  { city: "Makati", barangay: "Palanan" },
  { city: "Makati", barangay: "Pembo" },
  { city: "Makati", barangay: "Pinagkaisahan" },
  { city: "Makati", barangay: "Pio del Pilar" },
  { city: "Makati", barangay: "Pitogo" },
  { city: "Makati", barangay: "Poblacion" },
  { city: "Makati", barangay: "Post Proper Northside" },
  { city: "Makati", barangay: "Post Proper Southside" },
  { city: "Makati", barangay: "Rizal" },
  { city: "Makati", barangay: "San Antonio" },
  { city: "Makati", barangay: "San Isidro" },
  { city: "Makati", barangay: "San Lorenzo" },
  { city: "Makati", barangay: "Santa Cruz" },
  { city: "Makati", barangay: "Singkamas" },
  { city: "Makati", barangay: "South Cembo" },
  { city: "Makati", barangay: "Tejeros" },
  { city: "Makati", barangay: "Urdaneta" },
  { city: "Makati", barangay: "Valenzuela" },
  { city: "Makati", barangay: "West Rembo" },

  // Malabon
  { city: "Malabon", barangay: "Acacia" },
  { city: "Malabon", barangay: "Baritan" },
  { city: "Malabon", barangay: "Bayan-bayanan" },
  { city: "Malabon", barangay: "Catmon" },
  { city: "Malabon", barangay: "Concepcion" },
  { city: "Malabon", barangay: "Dampalit" },
  { city: "Malabon", barangay: "Flores" },
  { city: "Malabon", barangay: "Hulong Duhat" },
  { city: "Malabon", barangay: "Ibaba" },
  { city: "Malabon", barangay: "Longos" },
  { city: "Malabon", barangay: "Maysilo" },
  { city: "Malabon", barangay: "Muzon" },
  { city: "Malabon", barangay: "Niugan" },
  { city: "Malabon", barangay: "Panghulo" },
  { city: "Malabon", barangay: "Potrero" },
  { city: "Malabon", barangay: "San Agustin" },
  { city: "Malabon", barangay: "Santolan" },
  { city: "Malabon", barangay: "Ta�ong" },
  { city: "Malabon", barangay: "Tinajeros" },
  { city: "Malabon", barangay: "Tonsuya" },
  { city: "Malabon", barangay: "Tugatog" },

  // Mandaluyong
  { city: "Mandaluyong", barangay: "Addition Hills" },
  { city: "Mandaluyong", barangay: "Bagong Silang" },
  { city: "Mandaluyong", barangay: "Barangka Drive" },
  { city: "Mandaluyong", barangay: "Barangka Ibaba" },
  { city: "Mandaluyong", barangay: "Barangka Ilaya" },
  { city: "Mandaluyong", barangay: "Barangka Itaas" },
  { city: "Mandaluyong", barangay: "Buayang Bato" },
  { city: "Mandaluyong", barangay: "Burol" },
  { city: "Mandaluyong", barangay: "Daang Bakal" },
  { city: "Mandaluyong", barangay: "Hagdang Bato Itaas" },
  { city: "Mandaluyong", barangay: "Hagdang Bato Libis" },
  { city: "Mandaluyong", barangay: "Harapin Ang Bukas" },
  { city: "Mandaluyong", barangay: "Highway Hills" },
  { city: "Mandaluyong", barangay: "Hulo" },
  { city: "Mandaluyong", barangay: "Mabini-J. Rizal" },
  { city: "Mandaluyong", barangay: "Malamig" },
  { city: "Mandaluyong", barangay: "Mauway" },
  { city: "Mandaluyong", barangay: "Namayan" },
  { city: "Mandaluyong", barangay: "New Za�iga" },
  { city: "Mandaluyong", barangay: "Old Za�iga" },
  { city: "Mandaluyong", barangay: "Pag-asa" },
  { city: "Mandaluyong", barangay: "Plainview" },
  { city: "Mandaluyong", barangay: "Pleasant Hills" },
  { city: "Mandaluyong", barangay: "Poblacion" },
  { city: "Mandaluyong", barangay: "San Jose" },
  { city: "Mandaluyong", barangay: "Vergara" },
  { city: "Mandaluyong", barangay: "Wack-wack Greenhills" },

  // Marikina
  { city: "Marikina", barangay: "Barangka" },
  { city: "Marikina", barangay: "Calumpang" },
  { city: "Marikina", barangay: "Concepcion Dos" },
  { city: "Marikina", barangay: "Concepcion Uno" },
  { city: "Marikina", barangay: "Fortune" },
  { city: "Marikina", barangay: "Industrial Valley" },
  { city: "Marikina", barangay: "Jesus de La Pe�a" },
  { city: "Marikina", barangay: "Malanday" },
  { city: "Marikina", barangay: "Marikina Heights" },
  { city: "Marikina", barangay: "Nangka" },
  { city: "Marikina", barangay: "Parang" },
  { city: "Marikina", barangay: "San Roque" },
  { city: "Marikina", barangay: "Santa Elena" },
  { city: "Marikina", barangay: "Santo Ni�o" },
  { city: "Marikina", barangay: "Ta�ong" },
  { city: "Marikina", barangay: "Tumana" },

  // Muntinlupa
  { city: "Muntinlupa", barangay: "Alabang" },
  { city: "Muntinlupa", barangay: "Bayanan" },
  { city: "Muntinlupa", barangay: "Buli" },
  { city: "Muntinlupa", barangay: "Cupang" },
  { city: "Muntinlupa", barangay: "New Alabang Village" },
  { city: "Muntinlupa", barangay: "Poblacion" },
  { city: "Muntinlupa", barangay: "Putatan" },
  { city: "Muntinlupa", barangay: "Sucat" },
  { city: "Muntinlupa", barangay: "Tunasan" },

  // Navotas
  { city: "Navotas", barangay: "Bagumbayan North" },
  { city: "Navotas", barangay: "Bagumbayan South" },
  { city: "Navotas", barangay: "Bangculasi" },
  { city: "Navotas", barangay: "Daanghari" },
  { city: "Navotas", barangay: "NBBS Dagat-dagatan" },
  { city: "Navotas", barangay: "NBBS Kaunlaran" },
  { city: "Navotas", barangay: "NBBS Proper" },
  { city: "Navotas", barangay: "Navotas East" },
  { city: "Navotas", barangay: "Navotas West" },
  { city: "Navotas", barangay: "North Bay Boulevard North" },
  { city: "Navotas", barangay: "San Jose" },
  { city: "Navotas", barangay: "San Rafael Village" },
  { city: "Navotas", barangay: "San Roque" },
  { city: "Navotas", barangay: "Sipac-Almacen" },
  { city: "Navotas", barangay: "Tangos North" },
  { city: "Navotas", barangay: "Tangos South" },
  { city: "Navotas", barangay: "Tanza 1" },
  { city: "Navotas", barangay: "Tanza 2" },

  // Para�aque
  { city: "Para�aque", barangay: "B. F. Homes" },
  { city: "Para�aque", barangay: "Baclaran" },
  { city: "Para�aque", barangay: "Don Bosco" },
  { city: "Para�aque", barangay: "Don Galo" },
  { city: "Para�aque", barangay: "La Huerta" },
  { city: "Para�aque", barangay: "Marcelo Green Village" },
  { city: "Para�aque", barangay: "Merville" },
  { city: "Para�aque", barangay: "Moonwalk" },
  { city: "Para�aque", barangay: "San Antonio" },
  { city: "Para�aque", barangay: "San Dionisio" },
  { city: "Para�aque", barangay: "San Isidro" },
  { city: "Para�aque", barangay: "San Martin de Porres" },
  { city: "Para�aque", barangay: "Santo Ni�o" },
  { city: "Para�aque", barangay: "Sun Valley" },
  { city: "Para�aque", barangay: "Tambo" },
  { city: "Para�aque", barangay: "Vitalez" },

  // Pasig
  { city: "Pasig", barangay: "Bagong Ilog" },
  { city: "Pasig", barangay: "Bagong Katipunan" },
  { city: "Pasig", barangay: "Bambang" },
  { city: "Pasig", barangay: "Buting" },
  { city: "Pasig", barangay: "Caniogan" },
  { city: "Pasig", barangay: "Dela Paz" },
  { city: "Pasig", barangay: "Kalawaan" },
  { city: "Pasig", barangay: "Kapasigan" },
  { city: "Pasig", barangay: "Kapitolyo" },
  { city: "Pasig", barangay: "Malinao" },
  { city: "Pasig", barangay: "Manggahan" },
  { city: "Pasig", barangay: "Maybunga" },
  { city: "Pasig", barangay: "Oranbo" },
  { city: "Pasig", barangay: "Palatiw" },
  { city: "Pasig", barangay: "Pinagbuhatan" },
  { city: "Pasig", barangay: "Pineda" },
  { city: "Pasig", barangay: "Rosario" },
  { city: "Pasig", barangay: "Sagad" },
  { city: "Pasig", barangay: "San Antonio" },
  { city: "Pasig", barangay: "San Joaquin" },
  { city: "Pasig", barangay: "San Jose" },
  { city: "Pasig", barangay: "San Miguel" },
  { city: "Pasig", barangay: "San Nicolas" },
  { city: "Pasig", barangay: "Santa Cruz" },
  { city: "Pasig", barangay: "Santa Lucia" },
  { city: "Pasig", barangay: "Santa Rosa" },
  { city: "Pasig", barangay: "Santo Tomas" },
  { city: "Pasig", barangay: "Santolan" },
  { city: "Pasig", barangay: "Sumilang" },
  { city: "Pasig", barangay: "Ugong" },

  // Pateros
  { city: "Pateros", barangay: "Aguho" },
  { city: "Pateros", barangay: "Magtanggol" },
  { city: "Pateros", barangay: "Martires del 96" },
  { city: "Pateros", barangay: "Poblacion" },
  { city: "Pateros", barangay: "San Pedro" },
  { city: "Pateros", barangay: "San Roque" },
  { city: "Pateros", barangay: "Santa Ana" },
  { city: "Pateros", barangay: "Santo Rosario-Kanluran" },
  { city: "Pateros", barangay: "Santo Rosario-Silangan" },
  { city: "Pateros", barangay: "Tabacalera" },

  // Quezon City
  { city: "Quezon City", barangay: "Alicia" },
  { city: "Quezon City", barangay: "Amihan" },
  { city: "Quezon City", barangay: "Apolonio Samson" },
  { city: "Quezon City", barangay: "Aurora" },
  { city: "Quezon City", barangay: "Baesa" },
  { city: "Quezon City", barangay: "Bagbag" },
  { city: "Quezon City", barangay: "Bagong Lipunan ng Crame" },
  { city: "Quezon City", barangay: "Bagong Pag-asa" },
  { city: "Quezon City", barangay: "Bagong Silangan" },
  { city: "Quezon City", barangay: "Bagumbayan" },
  { city: "Quezon City", barangay: "Bagumbuhay" },
  { city: "Quezon City", barangay: "Bahay Toro" },
  { city: "Quezon City", barangay: "Balingasa" },
  { city: "Quezon City", barangay: "Balong Bato" },
  { city: "Quezon City", barangay: "Batasan Hills" },
  { city: "Quezon City", barangay: "Bayanihan" },
  { city: "Quezon City", barangay: "Blue Ridge A" },
  { city: "Quezon City", barangay: "Blue Ridge B" },
  { city: "Quezon City", barangay: "Botocan" },
  { city: "Quezon City", barangay: "Bungad" },
  { city: "Quezon City", barangay: "Camp Aguinaldo" },
  { city: "Quezon City", barangay: "Capri" },
  { city: "Quezon City", barangay: "Central" },
  { city: "Quezon City", barangay: "Claro" },
  { city: "Quezon City", barangay: "Commonwealth" },
  { city: "Quezon City", barangay: "Culiat" },
  { city: "Quezon City", barangay: "Damar" },
  { city: "Quezon City", barangay: "Damayan" },
  { city: "Quezon City", barangay: "Damayang Lagi" },
  { city: "Quezon City", barangay: "Del Monte" },
  { city: "Quezon City", barangay: "Dioquino Zobel" },
  { city: "Quezon City", barangay: "Don Manuel" },
  { city: "Quezon City", barangay: "Do�a Imelda" },
  { city: "Quezon City", barangay: "Do�a Josefa" },
  { city: "Quezon City", barangay: "Duyan-duyan" },
  { city: "Quezon City", barangay: "E. Rodriguez" },
  { city: "Quezon City", barangay: "East Kamias" },
  { city: "Quezon City", barangay: "Escopa I" },
  { city: "Quezon City", barangay: "Escopa II" },
  { city: "Quezon City", barangay: "Escopa III" },
  { city: "Quezon City", barangay: "Escopa IV" },
  { city: "Quezon City", barangay: "Fairview" },
  { city: "Quezon City", barangay: "Greater Lagro" },
  { city: "Quezon City", barangay: "Gulod" },
  { city: "Quezon City", barangay: "Holy Spirit" },
  { city: "Quezon City", barangay: "Horseshoe" },
  { city: "Quezon City", barangay: "Immaculate Concepcion" },
  { city: "Quezon City", barangay: "Kaligayahan" },
  { city: "Quezon City", barangay: "Kalusugan" },
  { city: "Quezon City", barangay: "Kamuning" },
  { city: "Quezon City", barangay: "Katipunan" },
  { city: "Quezon City", barangay: "Kaunlaran" },
  { city: "Quezon City", barangay: "Kristong Hari" },
  { city: "Quezon City", barangay: "Krus na Ligas" },
  { city: "Quezon City", barangay: "Laging Handa" },
  { city: "Quezon City", barangay: "Libis" },
  { city: "Quezon City", barangay: "Lourdes" },
  { city: "Quezon City", barangay: "Loyola Heights" },
  { city: "Quezon City", barangay: "Maharlika" },
  { city: "Quezon City", barangay: "Malaya" },
  { city: "Quezon City", barangay: "Mangga" },
  { city: "Quezon City", barangay: "Manresa" },
  { city: "Quezon City", barangay: "Mariana" },
  { city: "Quezon City", barangay: "Mariblo" },
  { city: "Quezon City", barangay: "Marilag" },
  { city: "Quezon City", barangay: "Masagana" },
  { city: "Quezon City", barangay: "Masambong" },
  { city: "Quezon City", barangay: "Matandang Balara" },
  { city: "Quezon City", barangay: "Milagrosa" },
  { city: "Quezon City", barangay: "N. S. Amoranto" },
  { city: "Quezon City", barangay: "Nagkaisang Nayon" },
  { city: "Quezon City", barangay: "Nayong Kanluran" },
  { city: "Quezon City", barangay: "New Era" },
  { city: "Quezon City", barangay: "North Fairview" },
  { city: "Quezon City", barangay: "Novaliches Proper" },
  { city: "Quezon City", barangay: "Obrero" },
  { city: "Quezon City", barangay: "Old Capitol Site" },
  { city: "Quezon City", barangay: "Paang Bundok" },
  { city: "Quezon City", barangay: "Pag-ibig sa Nayon" },
  { city: "Quezon City", barangay: "Paligsahan" },
  { city: "Quezon City", barangay: "Paltok" },
  { city: "Quezon City", barangay: "Pansol" },
  { city: "Quezon City", barangay: "Paraiso" },
  { city: "Quezon City", barangay: "Pasong Putik Proper" },
  { city: "Quezon City", barangay: "Pasong Tamo" },
  { city: "Quezon City", barangay: "Payatas" },
  { city: "Quezon City", barangay: "Phil-Am" },
  { city: "Quezon City", barangay: "Pinagkaisahan" },
  { city: "Quezon City", barangay: "Pinyahan" },
  { city: "Quezon City", barangay: "Project 6" },
  { city: "Quezon City", barangay: "Quirino 2-A" },
  { city: "Quezon City", barangay: "Quirino 2-B" },
  { city: "Quezon City", barangay: "Quirino 2-C" },
  { city: "Quezon City", barangay: "Quirino 3-A" },
  { city: "Quezon City", barangay: "Ramon Magsaysay" },
  { city: "Quezon City", barangay: "Roxas" },
  { city: "Quezon City", barangay: "Sacred Heart" },
  { city: "Quezon City", barangay: "Saint Ignatius" },
  { city: "Quezon City", barangay: "Saint Peter" },
  { city: "Quezon City", barangay: "Salvacion" },
  { city: "Quezon City", barangay: "San Agustin" },
  { city: "Quezon City", barangay: "San Antonio" },
  { city: "Quezon City", barangay: "San Bartolome" },
  { city: "Quezon City", barangay: "San Isidro" },
  { city: "Quezon City", barangay: "San Isidro Labrador" },
  { city: "Quezon City", barangay: "San Jose" },
  { city: "Quezon City", barangay: "San Martin de Porres" },
  { city: "Quezon City", barangay: "San Roque" },
  { city: "Quezon City", barangay: "San Vicente" },
  { city: "Quezon City", barangay: "Sangandaan" },
  { city: "Quezon City", barangay: "Santa Cruz" },
  { city: "Quezon City", barangay: "Santa Lucia" },
  { city: "Quezon City", barangay: "Santa Monica" },
  { city: "Quezon City", barangay: "Santa Teresita" },
  { city: "Quezon City", barangay: "Santo Cristo" },
  { city: "Quezon City", barangay: "Santo Domingo" },
  { city: "Quezon City", barangay: "Santo Ni�o" },
  { city: "Quezon City", barangay: "Santol" },
  { city: "Quezon City", barangay: "Sauyo" },
  { city: "Quezon City", barangay: "Sienna" },
  { city: "Quezon City", barangay: "Sikatuna Village" },
  { city: "Quezon City", barangay: "Silangan" },
  { city: "Quezon City", barangay: "Socorro" },
  { city: "Quezon City", barangay: "South Triangle" },
  { city: "Quezon City", barangay: "Tagumpay" },
  { city: "Quezon City", barangay: "Talayan" },
  { city: "Quezon City", barangay: "Talipapa" },
  { city: "Quezon City", barangay: "Tandang Sora" },
  { city: "Quezon City", barangay: "Tatalon" },
  { city: "Quezon City", barangay: "Teachers Village East" },
  { city: "Quezon City", barangay: "Teachers Village West" },
  { city: "Quezon City", barangay: "U.P. Campus" },
  { city: "Quezon City", barangay: "U.P. Village" },
  { city: "Quezon City", barangay: "Ugong Norte" },
  { city: "Quezon City", barangay: "Unang Sigaw" },
  { city: "Quezon City", barangay: "Valencia" },
  { city: "Quezon City", barangay: "Vasra" },
  { city: "Quezon City", barangay: "Veterans Village" },
  { city: "Quezon City", barangay: "Villa Maria Clara" },
  { city: "Quezon City", barangay: "West Kamias" },
  { city: "Quezon City", barangay: "West Triangle" },
  { city: "Quezon City", barangay: "White Plains" },

  // San Juan
  { city: "San Juan", barangay: "Addition Hills" },
  { city: "San Juan", barangay: "Balong-Bato" },
  { city: "San Juan", barangay: "Batis" },
  { city: "San Juan", barangay: "Corazon de Jesus" },
  { city: "San Juan", barangay: "Ermita�o" },
  { city: "San Juan", barangay: "Greenhills" },
  { city: "San Juan", barangay: "Halo-halo" },
  { city: "San Juan", barangay: "Isabelita" },
  { city: "San Juan", barangay: "Kabayanan" },
  { city: "San Juan", barangay: "Little Baguio" },
  { city: "San Juan", barangay: "Maytunas" },
  { city: "San Juan", barangay: "Onse" },
  { city: "San Juan", barangay: "Pasade�a" },
  { city: "San Juan", barangay: "Pedro Cruz" },
  { city: "San Juan", barangay: "Progreso" },
  { city: "San Juan", barangay: "Rivera" },
  { city: "San Juan", barangay: "Salapan" },
  { city: "San Juan", barangay: "San Perfecto" },
  { city: "San Juan", barangay: "Santa Lucia" },
  { city: "San Juan", barangay: "Tibagan" },
  { city: "San Juan", barangay: "West Crame" },

  // Taguig
  { city: "Taguig", barangay: "Bagumbayan" },
  { city: "Taguig", barangay: "Bambang" },
  { city: "Taguig", barangay: "Calzada" },
  { city: "Taguig", barangay: "Central Bicutan" },
  { city: "Taguig", barangay: "Central Signal Village" },
  { city: "Taguig", barangay: "Fort Bonifacio" },
  { city: "Taguig", barangay: "Hagonoy" },
  { city: "Taguig", barangay: "Ibayo-Tipas" },
  { city: "Taguig", barangay: "Katuparan" },
  { city: "Taguig", barangay: "Ligid-Tipas" },
  { city: "Taguig", barangay: "Lower Bicutan" },
  { city: "Taguig", barangay: "Maharlika Village" },
  { city: "Taguig", barangay: "Napindan" },
  { city: "Taguig", barangay: "New Lower Bicutan" },
  { city: "Taguig", barangay: "North Daang Hari" },
  { city: "Taguig", barangay: "North Signal Village" },
  { city: "Taguig", barangay: "Palingon" },
  { city: "Taguig", barangay: "Pinagsama" },
  { city: "Taguig", barangay: "San Miguel" },
  { city: "Taguig", barangay: "Santa Ana" },
  { city: "Taguig", barangay: "South Daang Hari" },
  { city: "Taguig", barangay: "South Signal Village" },
  { city: "Taguig", barangay: "Tanyag" },
  { city: "Taguig", barangay: "Tuktukan" },
  { city: "Taguig", barangay: "Upper Bicutan" },
  { city: "Taguig", barangay: "Ususan" },
  { city: "Taguig", barangay: "Wawa" },
  { city: "Taguig", barangay: "Western Bicutan" },

  // Valenzuela
  { city: "Valenzuela", barangay: "Arkong Bato" },
  { city: "Valenzuela", barangay: "Bagbaguin" },
  { city: "Valenzuela", barangay: "Balangkas" },
  { city: "Valenzuela", barangay: "Bignay" },
  { city: "Valenzuela", barangay: "Bisig" },
  { city: "Valenzuela", barangay: "Canumay East" },
  { city: "Valenzuela", barangay: "Canumay West" },
  { city: "Valenzuela", barangay: "Coloong" },
  { city: "Valenzuela", barangay: "Dalandanan" },
  { city: "Valenzuela", barangay: "Gen. T. de Leon" },
  { city: "Valenzuela", barangay: "Isla" },
  { city: "Valenzuela", barangay: "Karuhatan" },
  { city: "Valenzuela", barangay: "Lawang Bato" },
  { city: "Valenzuela", barangay: "Lingunan" },
  { city: "Valenzuela", barangay: "Mabolo" },
  { city: "Valenzuela", barangay: "Malanday" },
  { city: "Valenzuela", barangay: "Malinta" },
  { city: "Valenzuela", barangay: "Mapulang Lupa" },
  { city: "Valenzuela", barangay: "Marulas" },
  { city: "Valenzuela", barangay: "Maysan" },
  { city: "Valenzuela", barangay: "Palasan" },
  { city: "Valenzuela", barangay: "Parada" },
  { city: "Valenzuela", barangay: "Pariancillo Villa" },
  { city: "Valenzuela", barangay: "Paso de Blas" },
  { city: "Valenzuela", barangay: "Pasolo" },
  { city: "Valenzuela", barangay: "Poblacion" },
  { city: "Valenzuela", barangay: "Pulo" },
  { city: "Valenzuela", barangay: "Punturin" },
  { city: "Valenzuela", barangay: "Rincon" },
  { city: "Valenzuela", barangay: "Tagalag" },
  { city: "Valenzuela", barangay: "Ugong" },
  { city: "Valenzuela", barangay: "Viente Reales" },
  { city: "Valenzuela", barangay: "Wawang Pulo" },
];

const numberedLocations = [
  ...buildNumberedBarangays("Caloocan", 1, 188),
  ...buildNumberedBarangays("Manila", 1, 905, [
    "Barangay 202-A",
    "Barangay 587-A",
    "Barangay 659-A",
    "Barangay 660-A",
    "Barangay 663-A",
    "Barangay 664-A",
    "Barangay 818-A",
  ]),
  ...buildNumberedBarangays("Pasay", 1, 201),
];

const allLocations = [...namedLocations, ...numberedLocations];

export const CITY_TO_BARANGAYS: Record<string, string[]> = allLocations.reduce(
  (acc, item) => {
    const existing = acc[item.city] || [];
    if (!existing.includes(item.barangay)) {
      existing.push(item.barangay);
    }
    acc[item.city] = existing;
    return acc;
  },
  {} as Record<string, string[]>,
);

export const NCR_CITIES = Object.keys(CITY_TO_BARANGAYS).sort((a, b) =>
  a.localeCompare(b),
);

export const ORGANIZATION_OPTIONS = [
  { label: "Police Department", value: "Police" },
  { label: "Barangay Response Team", value: "Barangay" },
] as const;
